### ISSUE TITLE
Unable to transcribe, recipe says journal needs to be (decayed)

### ISSUE THREAD

**Issue by Ploglo** [Chuckleberry-Finn/Skill-Recovery-Journal#71]
Mod was working great on 2 different saves before this. Now I've been unable to transcribe and when I check the crafting recipe it tells me the journal must be (decayed) to transcribe. Is there a way to either make my journal (decayed) or make it so the crafting recipe doesn't require it to be? here is my error log, it generates a new error about once every quarter of a second if my character reads the journal
[Uploading console.txt…]()

**Comment by Ploglo** [comment]
File didn't upload properly so here's the error message:
Callframe at: table.pairs
function: update -- file: Skill Recovery Journal Reading.lua line # 124 | MOD: Skill Recovery Journal

ERROR: General     , 1704156123703> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: Expected a table at KahluaUtil.fail line:82.
ERROR: General     , 1704156123704> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: Expected a table
	at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
	at se.krka.kahlua.vm.KahluaUtil.luaAssert(KahluaUtil.java:70)
	at se.krka.kahlua.stdlib.TableLib.pairs(TableLib.java:119)
	at se.krka.kahlua.stdlib.TableLib.call(TableLib.java:95)
	at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1827)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:38)
	at zombie.characters.CharacterTimedActions.LuaTimedActionNew.update(LuaTimedActionNew.java:70)
	at zombie.characters.IsoGameCharacter.updateInternal(IsoGameCharacter.java:9719)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.characters.IsoGameCharacter.update(IsoGameCharacter.java:9464)
	at zombie.characters.IsoPlayer.updateInternal1(IsoPlayer.java:1943)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.characters.IsoPlayer.update(IsoPlayer.java:1924)
	at zombie.MovingObjectUpdateSchedulerUpdateBucket.update(MovingObjectUpdateSchedulerUpdateBucket.java:79)
	at zombie.MovingObjectUpdateScheduler.update(MovingObjectUpdateScheduler.java:145)
	at zombie.iso.IsoCell.ProcessObjects(IsoCell.java:2955)
	at zombie.iso.IsoCell.updateInternal(IsoCell.java:5750)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.iso.IsoCell.update(IsoCell.java:5696)
	at zombie.iso.IsoWorld.updateInternal(IsoWorld.java:3499)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.iso.IsoWorld.update(IsoWorld.java:3427)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1617)
	at zombie.gameStates.IngameState.update(IngameState.java:1333)
	at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
	at zombie.GameWindow.logic(GameWindow.java:298)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:765)
	at zombie.GameWindow.run_ez(GameWindow.java:681)
	at zombie.GameWindow.mainThread(GameWindow.java:495)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1704156123710> -----------------------------------------
STACK TRACE
-----------------------------------------
Callframe at: table.pairs
function: update -- file: Skill Recovery Journal Reading.lua line # 124 | MOD: Skill Recovery Journal

LOG  : General     , 1704156137251> EXITDEBUG: setGameSpeed 1
LOG  : General     , 1704156137251> EXITDEBUG: setGameSpeed 3
LOG  : General     , 1704156137252> [ssr-examine] 	EXITDEBUG: ToggleEscapeMenu 1
LOG  : General     , 1704156137252> [ssr-examine] 	EXITDEBUG: ToggleEscapeMenu 3
LOG  : General     , 1704156137252> [ssr-examine] 	EXITDEBUG: ToggleEscapeMenu 4
LOG  : General     , 1704156137253> [ssr-examine] 	EXITDEBUG: ToggleEscapeMenu 5
LOG  : General     , 1704156137253> EXITDEBUG: setGameSpeed 1
LOG  : General     , 1704156137254> EXITDEBUG: setGameSpeed 3
LOG  : General     , 1704156137254> EXITDEBUG: setShowPausedMessage 1
LOG  : General     , 1704156137254> EXITDEBUG: setShowPausedMessage 2

**Comment by Chuckleberry-Finn** [comment]
Can you screenshot the recipe page?

**Comment by Ammitz** [comment]
https://steamcommunity.com/id/kasboell/screenshot/2267065063342495531/
https://steamcommunity.com/id/kasboell/screenshot/2267065063342493214/

**Comment by Chuckleberry-Finn** [comment]
Your screenshot does not show the recipe needs a decayed journal. I'm not sure why the context menu is breaking for your game.
