### ISSUE TITLE
ToolTipInv / ToolTip.lua errors

### ISSUE THREAD

**Issue by Shakiereagle** [Chuckleberry-Finn/Skill-Recovery-Journal#73]
**This is not particularly related to this mod but it is involved and I might get help**, as Noir's attachments mod has their comments disabled and Snake modpacks is quite unhelpful. Anyways, there are some clothes such as Vests and Jackets that when I put my cursor over them, the stats become invisible and the game starts spamming me errors (Up to 3000) But nothing really happens. It stops spamming and it shows my stats when I put the clothing on. The only thing I noticed from the logs is that they're all related to the tooltip UI itself, as I don't think these mods have anything somewhat similar on their funcionality. I don't know anything about these codes but maybe I could get what's causing it, if an overlap of mods or incompatibilities, which is odd because I've been playing for 2 weeks with this modpack and never got an error until now.

Thank you very much in advance. I hope you can figure out what could be happening.

Callframe at: se.krka.kahlua.integration.expose.MultiLuaJavaInvoker@6960e303
function: render -- file: ISToolTipInv.lua line # 108 | Vanilla
function: render -- file: Skill Recovery Journal Tooltip.lua line # 276 | MOD: Skill Recovery Journal
function: render -- file: tooltip.lua line # 879 | MOD: Snake's ModPack - Pack de Utilidades de Snake V1.37
function: render -- file: zNATT_Tooltip.lua line # 43 | MOD: Noir's Attachments

ERROR: General     , 1705559061589> 62,217,210> ExceptionLogger.logException> Exception thrown java.lang.reflect.InvocationTargetException at GeneratedMethodAccessor2568.invoke.
ERROR: General     , 1705559061590> 62,217,210> DebugLogStream.printException> Stack trace:
java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor2568.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at se.krka.kahlua.integration.expose.caller.MethodCaller.call(MethodCaller.java:62)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:198)
	at se.krka.kahlua.integration.expose.MultiLuaJavaInvoker.call(MultiLuaJavaInvoker.java:60)
	at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1827)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:38)
	at zombie.ui.UIElement.render(UIElement.java:1534)
	at zombie.ui.UIManager.render(UIManager.java:446)
	at zombie.gameStates.IngameState.renderFrameUI(IngameState.java:1183)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.gameStates.IngameState.renderframeui(IngameState.java:1172)
	at zombie.gameStates.IngameState.renderInternal(IngameState.java:1324)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.gameStates.IngameState.render(IngameState.java:1271)
	at zombie.gameStates.GameStateMachine.render(GameStateMachine.java:37)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.GameWindow.renderInternal(GameWindow.java:340)
	at zombie.GameWindow.frameStep(GameWindow.java:774)
	at zombie.GameWindow.run_ez(GameWindow.java:667)
	at zombie.GameWindow.mainThread(GameWindow.java:495)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: class zombie.inventory.types.InventoryContainer cannot be cast to class zombie.inventory.types.Clothing (zombie.inventory.types.InventoryContainer and zombie.inventory.types.Clothing are in unnamed module of loader 'app')
	at zombie.inventory.types.Clothing.DoTooltip(Clothing.java:237)
	at zombie.inventory.InventoryItem.DoTooltip(InventoryItem.java:619)
	... 45 more
LOG  : General     , 1705559061592> 62,217,213> -----------------------------------------
STACK TRACE

**Comment by Chuckleberry-Finn** [comment]
https://www.reddit.com/r/projectzomboid/comments/199sxak/psa_regarding_tooltip_render_spamming_errors/
