### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by xDeCkSx** [Chuckleberry-Finn/Skill-Recovery-Journal#78]
LOG  : General     , 1718752769368> 197.973.910> -----------------------------------------
STACK TRACE
-----------------------------------------
function: update -- file: Skill Recovery Journal Reading.lua line # 231 | MOD: Skill Recovery Journal

LOG  : General     , 1718752769578> 197.974.119> -----------------------------------------
STACK TRACE
-----------------------------------------
function: update -- file: Skill Recovery Journal Reading.lua line # 231 | MOD: Skill Recovery Journal

ERROR: General     , 1718752769578> 197.974.120> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: __lt not defined for operand at KahluaUtil.fail line:82.
ERROR: General     , 1718752769578> 197.974.120> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: __lt not defined for operand
at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:900)
at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1827)
at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:38)
at zombie.characters.CharacterTimedActions.LuaTimedActionNew.update(LuaTimedActionNew.java:70)
at zombie.characters.IsoGameCharacter.updateInternal(IsoGameCharacter.java:9719)
at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
at zombie.util.Lambda.capture(Lambda.java:130)
at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
at zombie.characters.IsoGameCharacter.update(IsoGameCharacter.java:9464)
at zombie.characters.IsoPlayer.updateInternal1(IsoPlayer.java:1943)
at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
at zombie.util.Lambda.capture(Lambda.java:130)
at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
at zombie.characters.IsoPlayer.update(IsoPlayer.java:1924)
at zombie.MovingObjectUpdateSchedulerUpdateBucket.update(MovingObjectUpdateSchedulerUpdateBucket.java:79)
at zombie.MovingObjectUpdateScheduler.update(MovingObjectUpdateScheduler.java:145)
at zombie.iso.IsoCell.ProcessObjects(IsoCell.java:2955)
at zombie.iso.IsoCell.updateInternal(IsoCell.java:5750)
at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
at zombie.util.Lambda.capture(Lambda.java:130)
at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
at zombie.iso.IsoCell.update(IsoCell.java:5696)
at zombie.iso.IsoWorld.updateInternal(IsoWorld.java:3499)
at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
at zombie.util.Lambda.capture(Lambda.java:130)
at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
at zombie.iso.IsoWorld.update(IsoWorld.java:3427)
at zombie.gameStates.IngameState.updateInternal(IngameState.java:1617)
at zombie.gameStates.IngameState.update(IngameState.java:1333)
at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
at zombie.GameWindow.logic(GameWindow.java:298)
at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
at zombie.GameWindow.frameStep(GameWindow.java:765)
at zombie.GameWindow.run_ez(GameWindow.java:667)
at zombie.GameWindow.mainThread(GameWindow.java:495)
at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1718752769580> 197.974.121> -----------------------------------------
STACK TRACE
-----------------------------------------
function: update -- file: Skill Recovery Journal Reading.lua line # 231 | MOD: Skill Recovery Journal

**Comment by xDeCkSx** [comment]
Can help ?

**Comment by Chuckleberry-Finn** [comment]
Try changing/editing the sandbox options, it should add the missing setting.
